### ISSUE TITLE
world specific crashing

### ISSUE THREAD

**Issue by Malthbern** [l-404-l/Portal-Confirmation#1]
every time i attempted to load [this world](https://www.vrchat.com/home/world/wrld_9f966e9f-6058-40a9-be04-9fa90bbda0a4) it caused an error that immediately crashed melon and VRC. here's the log file if it helps
[MelonLoader_20-06-22_01-47-33.791.log](https://github.com/l-404-l/Portal-Confirmation/files/4812292/MelonLoader_20-06-22_01-47-33.791.log)

**Comment by l-404-l** [comment]
This is someones world crash report it to vrchat.
